(globals
	version = 3
	io_order = clockwise
)
(iopad
	(topleft
		(inst name="dsm_dem_pad0/ulcorner_pad")
	)

	(top
		(inst name="dsm_dem_pad0/dsm_chan10_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan11_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan12_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan13_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan14_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan15_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan16_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan17_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan18_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan19_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan110_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan111_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan112_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan113_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan114_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan115_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan116_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan117_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan118_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan119_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan120_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan121_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan122_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan123_pad" space=0 place_status=placed)
	)

	(topright
		(inst name="dsm_dem_pad0/urcorner_pad")
	)

	(right
		(inst name="dsm_dem_pad0/dem_out_l0_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l1_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l2_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l3_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l4_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l5_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l6_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l7_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l8_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l9_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l10_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l11_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r0_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r1_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r2_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r3_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r4_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r5_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r6_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r7_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r8_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r9_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r10_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r11_pad" 	space=0 place_status=placed)
	)
	(bottomright
		(inst name="dsm_dem_pad0/lrcorner_pad")
	)
	(left
		(inst name="dsm_dem_pad0/mclk512_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/reset_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/exchangeLR_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_clr_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsmditheroff_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_count0_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_count1_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vss_pad1" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vssior_pad1" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vddior_pad1" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vdd_pad1" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vss_pad0"    space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vssior_pad0" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vddior_pad0" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/vdd_pad0"    space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_ovfl_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r12_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r13_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r14_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_r15_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l12_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l13_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l14_pad" 	space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dem_out_l15_pad" 	space=0 place_status=placed)
	)
	(bottomleft
		(inst name="dsm_dem_pad0/llcorner_pad")
	)
	(bottom
		(inst name="dsm_dem_pad0/dsm_chan20_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan21_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan22_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan23_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan24_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan25_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan26_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan27_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan28_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan29_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan210_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan211_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan212_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan213_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan214_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan215_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan216_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan217_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan218_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan219_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan220_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan221_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan222_pad" space=0 place_status=placed)
		(inst name="dsm_dem_pad0/dsm_chan223_pad" space=0 place_status=placed)
	)
)
